### ISSUE TITLE
Definitions from 22989

### ISSUE THREAD

**Issue by hollobit** [hollobit/WG3_TCM#4]
There are missed definitions from clause 3.4 of 22989
- 3.4.2 accountability
- 3.4.3 availability
- 3.4.5 control
- 3.4.6 explainability
- 3.4.7 predictability
- 3.4.8 reliability
- 3.4.9 resilience
- 3.4.11 robustness
- 3.4.12 safety
- 3.4.14 transparency
- 3.4.15 transparency
- 3.4.16 trustworthiness
- 3.4.17 verification
- 3.4.18 validation

We need to add "D" in the related 22989 columns of terms.

**Comment by paulbrucecotton** [comment]
We may need to determine if there is a preferred definition when multiple documents define the same term in different ways.  For example I would strongly prefer to emphasize the definitions in ISO/IEC 22989:2022 over definitions from older SC 42 documents but others may have different opinions on this.

/paulc

**Comment by harm-ellens** [comment]
Agreed. Refer my comment on #8
